### ISSUE TITLE
v3/v4 endpoints

### ISSUE THREAD

**Issue by elmobp** [stevevillardi/Logic.Monitor#1]
Quick question for this... Given "v3" is technically unsupported as its not documented where can we get a extract of the swagger doc for v3?

**Comment by stevevillardi** [comment]
I don't believe there has been an official swagger document created for v3. I know they are working on updating the swagger documentation overall but do not have much more insight than that unfortunately.

**Comment by stevevillardi** [comment]
@elmobp I know this was quite a bit ago but just wanted to let you know the swagger guide for API v3 has been released and is available at: [LogicMonitor API v3](https://www.logicmonitor.com/swagger-ui-master/api-v3/dist/)

**Comment by elmobp** [comment]
@stevevillardi  yeh funily enough we are using v4 endpoints now and v3 has only just been published

**Comment by stevevillardi** [comment]
Yea v4 is a totally different beast, I use it in some places where I have no choice but its not really intended for automation as its response model is built around UI driven usage but my understanding is v3 will be the default customer facing API endpoint going forward with new endpoints being added to v3 that don't exist today.

**Comment by elmobp** [comment]
I actually found a issue with v4 today... We must of swapped to 179 recently what was returning a device name in 178 is returning the IP address in 179.. I see what you mean :/
