### ISSUE TITLE
Upgrade from V1 API to V3 API 

### ISSUE THREAD

**Issue by h3steinhauer** [stevevillardi/Logic.Monitor#12]
Where is upgrading from V1 API to the V3 API? 

The Login process of V1 is supposed to go away and I was hoping that you would have the V3 API process soon 
Any timeline for expectations?

**Comment by stevevillardi** [comment]
Are you referring to the LMv1 authentication mechanism or v1 of the LM API? This module already strictly uses version 3 of the LM API which can use either LMv1 auth or Bearer token.  To use bearer token you need to supply the parameter -BearerToken when running the Connect-LMAccount command.
