### ISSUE TITLE
Add URL to LMWebsite

### ISSUE THREAD

**Issue by cainef** [stevevillardi/Logic.Monitor#13]
By default the Set-LMWebsite and New-LMWebsite create a step using the root domain only
We monitor a lot of websites using healthcheck or version endpoints as part of the uri. 

It would be good if we could have a parameter that allows us to set the URL portion of the step when creating or updating an LM website. 

https://github.com/stevevillardi/Logic.Monitor/blob/851a64fd0179480b49d79852b41c7abec585e7bb/Public/New-LMWebsite.ps1#L85

![image](https://github.com/stevevillardi/Logic.Monitor/assets/14501795/e88a3dd5-6271-45a7-a685-6ca39fa66fe3)

**Comment by stevevillardi** [comment]
When those were first published they were very barebones in terms of accepted parameters since at the time were not heavily requested commands. I have been meaning to re work them to allow for more options and flexibility for both internal and external webchecks. I will try and get to that in the next module update. Thanks for the feedback!

**Comment by cainef** [comment]
Really appreciate that, this module has been an absolute time saver. We were using our own functions after having issues with the old LogicMonitor module, but this is much better. Great work.

**Comment by stevevillardi** [comment]
No problem glad you find it valuable! If you have not already please relay that feedback to your customer success manager. I am trying to show that the demand for a LM supported module is out there and any feedback from customers goes a long way in making that a reality.

**Comment by stevevillardi** [comment]
So in the newest release 4.4 there is a webchecksteps object you can now provide that allows you to specify all the require step settings.
